apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world

spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world

  template:
    metadata:
      labels:
        app: hello-world

    spec:
      containers:
        - name: hello-world
          image: jduun/hello-world:0.1@sha256:9d8d791b56b1cc8e6353d4fb5c4797a06412a4dd4f4107b7ccadde02c2acb629
          ports:
            - containerPort: 32777

          readinessProbe:
            httpGet:
              path: /
              port: 32777
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 32777
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
