replicaCount: 2

image:
  repository: jduun/hello-world
  tag: "0.1.0"
  digest: sha256:5fb84584ca03014a8f42faeb504726cae02035dee38119fc596b069d088981d7
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 32777

resources:
  requests:
    cpu: "10m"
    memory: "16Mi"
  limits:
    cpu: "100m"
    memory: "64Mi"

probes:
  readiness:
    path: /ready
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 5

  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 5

serviceMonitor:
  enabled: true
  path: /metrics
  interval: 15s
  labels:
    release: monitoring

alerts:
  enabled: true
  labels:
    release: monitoring

  serviceDown:
    for: 20s

  restarts:
    window: 10m
    for: 0m

  cpu:
    threshold: 0.8
    for: 5m

  memory:
    threshold: 0.8
    for: 5m
